//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int cart_id { get; set; }
        public string customer_name { get; set; }
        public string phone_number { get; set; }
        public string place_of_receipt { get; set; }
        public string note { get; set; }
        public string payment_method { get; set; }
        public decimal total_price { get; set; }
        public int delivery_status_id { get; set; }
        public int is_paid { get; set; }
        public decimal ship_price { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> creator_id { get; set; }
    
        public virtual Delivery_status Delivery_status { get; set; }
        public virtual Order_Product Order_Product { get; set; }
        public virtual User User { get; set; }
    }
}
