//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Product = new HashSet<Order_Product>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string short_desc { get; set; }
        public string images { get; set; }
        public int specs_id { get; set; }
        public decimal price { get; set; }
        public int promotion_id { get; set; }
        public int category_id { get; set; }
        public string cpu { get; set; }
        public string gpu { get; set; }
        public string screen { get; set; }
        public string storage { get; set; }
        public string ram { get; set; }
        public string os { get; set; }
        public string size { get; set; }
        public string weight { get; set; }
        public string ports { get; set; }
        public string connectivity { get; set; }
        public string battery { get; set; }
        public string extras { get; set; }
        public string manufacturer { get; set; }
        public System.DateTime MFG { get; set; }
        public int quantity { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Product> Order_Product { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
